[package]
name = "iron-sessionstorage"
version = "0.2.1"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["iron", "sessions", "cookie", "user", "login"]
readme = "README.md"

description = "Basic session middleware for Iron."
repository = "https://github.com/untitaker/iron-sessionstorage"
homepage = "https://github.com/untitaker/iron-sessionstorage"

[dependencies]
iron = "0.4"

[dependencies.cookie]
version = "0.2.2"
features = ["secure"]
